[package]
name = "pleblottery"
authors = [ "plebhash <plebhash@proton.me>" ]
version = "0.1.0"
edition = "2021"
description = "a hashrate aggregator for a pleb-friendly and fully sovereign solo/lottery Bitcoin mining experience"

[dependencies]
# async
tokio = { version = "1", features = ["full"] }

# tracing
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }